Feature: client test suite
openqda/openqda pull request #25
Opened 2024-05-17 10:05 UTC by jankapunkt

This adds basic unit tests (via vitest) and e2e tests (via cypress) to the client.

2024-05-22 11:26 UTC, alessandrobelli commented
Is there a quick way for me to test this?

We should add a testing documentation, it can even be extremely short, such as "to run frontend test run this command ..." - "to run backend test run this command ...".

2024-05-22 12:04 UTC, jankapunkt commented
@alessandrobelli you're absolutely right about this, I added a testing guide to the docs. You should be able to reproduce everything using the guide.

2024-05-25 04:56 UTC, jankapunkt commented
@alessandrobelli could you please check this again, I have added a testing guide already :-)

2024-05-27 09:30 UTC, alessandrobelli requested changes

2024-05-27 09:30 UTC, alessandrobelli commented on web/cypress/e2e/1-getting-started/login.cy.js
> +        cy.visit('http://localhost')
The e2e tests they are returning an error because cypress is looking for http://localhost, can we have cypress checking the env file for APP_URL parameter?

```
====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  login.cy.js                              413ms        3        -        1        -        2 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     413ms        3        -        1        -        2  

```

2024-05-27 09:31 UTC, alessandrobelli commented
Also I get this when running unit tests:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.

```

But this might be just a node problem. After I deleted node modules and installed again, it worked.

2024-05-27 09:45 UTC, jankapunkt commented on web/cypress/e2e/1-getting-started/login.cy.js
> +        cy.visit('http://localhost')
Why is localhost a problem? Isn't this the default url to open the dev website?

2024-05-28 09:41 UTC, jankapunkt commented on web/cypress/e2e/1-getting-started/login.cy.js
> +        cy.visit('http://localhost')
@alessandrobelli I found something: https://docs.cypress.io/guides/guides/environment-variables#Option-4---env I will make this configurable

2024-06-03 11:07 UTC, alessandrobelli commented on web/cypress/e2e/1-getting-started/login.cy.js
> +        cy.visit('http://localhost')
```
  1) open qda welcome page
       "before each" hook for "displays the welcome screen by default":
     CypressError: `cy.visit()` failed trying to load:

web.test

We failed looking for this file at the path:

/Users/belli/code/openqda/web/web.test

The internal Cypress web server responded with:

  > 404: Not Found
```

I got this error trying to run with the custom env,like this:
`npm run test:e2e -- host=web.test`

on the other hand, `npx cypress open --env host=web.test ` now loads, and I see many 200 in the console, but the tests are still "on load"

```
belli@MacBook-Pro-2 openqda/web (feature/tests-client !*) » npx cypress open --env host=web.test                                                                                                                1 ↵

DevTools listening on ws://127.0.0.1:53149/devtools/browser/c67d307e-37eb-49f7-a145-3a857eea9836
2024-06-03 13:02:15.272 Cypress[5851:3301726] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  LARAVEL v11.0.7  plugin v1.0.4

  ➜  APP_URL: https://web.test
  ➜  Using Herd certificate to secure Vite.
GET /__/ 200 1.679 ms - -
GET /__/assets/index-3fd9e8ed.css 200 0.841 ms - -
GET /__/assets/polyfills-3023ae52.js 200 4.280 ms - -
GET /__/assets/index-3fe21bb9.js 200 0.927 ms - -
GET /chains/remote-settings.content-signature.mozilla.org-2024-06-29-17-33-44.chain 200 584.395 ms - -
GET /__cypress/runner/cypress_runner.css 200 1.385 ms - -
GET /__/assets/Specs-4115352f.js 200 2.402 ms - 523
GET /__/assets/route-block-c0a8bdd8.js 200 2.117 ms - 45
GET /__/assets/box-open_x48-5f9fb7b5.js 200 2.640 ms - -
GET /__/assets/graphql-5752d761.js 200 2.464 ms - 535
GET /__/assets/InlineCodeFragment-63f519c9.css 200 2.866 ms - 310
GET /__/assets/TrackedBanner.vue_vue_type_script_setup_true_lang-5951d338.js 200 3.554 ms - -
GET /__/assets/SpecPatterns.vue_vue_type_script_setup_true_lang-27b38053.js 200 3.539 ms - -
GET /__/assets/Index-f90bad12.css 200 2.437 ms - -
GET /__/assets/SpecNameDisplay.vue_vue_type_script_setup_true_lang-9e6cef72.js 200 2.508 ms - -
GET /__/assets/settings_x16-a9b74cd2.js 200 2.725 ms - -
GET /__/assets/PromoHeader.vue_vue_type_script_setup_true_lang-1bb58a00.js 200 2.933 ms - -
GET /__/assets/InlineCodeFragment.vue_vue_type_script_setup_true_lang-2ebf3d7b.js 200 3.013 ms - -
GET /__/assets/Index-61c9d6a8.js 200 3.620 ms - -
GET /v1/buckets/main/collections/ms-language-packs/records/cfr-v1-en-GB 200 563.140 ms - -
GET /__/assets/cypress_s-29af549a.png 200 7.465 ms - 4425
GET /__/assets/firefox-9be61e66.svg 200 2.907 ms - -
GET /__/assets/chrome-98045c79.svg 200 2.498 ms - -
GET /__/assets/electron-fb07f5cc.svg 200 2.418 ms - -
GET /__cypress/runner/favicon.ico?v2 200 2.334 ms - -
GET /__cypress/runner/cypress_runner.js 200 1.503 ms - -
GET /__/assets/Switch.vue_vue_type_script_setup_true_lang-aa15826b.js 200 1.421 ms - -
GET /__/assets/Runner-d26b5796.css 200 1.293 ms - -
GET /__/assets/refresh_x16-963a23f0.js 200 1.891 ms - -
GET /__/assets/Runner-888097d3.js 200 1.684 ms - -
```
<img width="1800" alt="Screenshot 2024-06-03 at 13 07 36" src="https://github.com/openqda/openqda/assets/3796324/a7131209-a64f-490e-945e-ddb4369862c3">

2024-06-03 11:38 UTC, jankapunkt commented on web/cypress/e2e/1-getting-started/login.cy.js
> +        cy.visit('http://localhost')
Weird. My proposal: remove e2e tests from this pull request and merge the rest so we have client tests in our CI and I will add e2e tests separately, once we got it running. what do you think?

2024-06-03 11:43 UTC, alessandrobelli commented on web/cypress/e2e/1-getting-started/login.cy.js
> +        cy.visit('http://localhost')
sure 👍

2024-06-04 17:38 UTC, jankapunkt commented
@alessandrobelli I removed e2e for now as we have some full-stack tests already with pest and the e2e make more sense, once we have the new design and layout implemented.

2024-06-06 10:14 UTC, alessandrobelli approved these changes
`npx cypress open --env host=web.test` is running, but I can't see anything, as for the comment https://github.com/openqda/openqda/pull/25#discussion_r1624236352 .
Maybe it's on my end, anyway I will approve

2024-06-06 10:43 UTC, merged