Add Import/Export Functionality for Codebooks with Basic UI
openqda/openqda pull request #35
Opened 2024-05-27 10:12 UTC by alessandrobelli

This pull request adds the import and export functionality for codebooks via the `CodebookCodesController`. It also includes a basic UI for these operations, anticipating a more comprehensive UI update later.

The export button is in each Codebook.

To test this, you probably need to have any QDA software, [f4analyse](https://www.audiotranskription.de/en/f4analyse/) has a free trial.

I manually tested exporting from many software products, including:
- maxqda
- nvivo
- atlas.ti
- f4analyse

2024-05-27 10:13 UTC, alessandrobelli commented
Address https://github.com/openqda/openqda/issues/8

2024-05-27 11:54 UTC, jankapunkt commented
I think it would be best to publish this branch to staging and let @hohse and @GinKru91 test the functionality from a domain-expert perspective and I will review from a code-perspective. What do you think @alessandrobelli

2024-05-27 12:35 UTC, alessandrobelli commented
@hohse and @GinKru91 change is live on the staging server

2024-05-28 06:56 UTC, jankapunkt requested changes

2024-05-28 06:56 UTC, jankapunkt commented on web/composer.json
> +        "ext-simplexml": "*"
We should always pin the exact version to avoid automatic version bumps and "supply chain attacks"

- https://go.snyk.io/rs/677-THP-415/images/2023%20Software%20Supply%20Chain%20Attack%20Report%20Snyk.pdf

2024-05-28 06:56 UTC, jankapunkt commented on web/app/Http/Controllers/CodebookCodesController.php
> +class CodebookCodesController extends Controller
I personally would prefer, that the word `Import` appears somewhere in the class name, however Optional for now.

2024-05-28 07:28 UTC, alessandrobelli commented on web/app/Http/Controllers/CodebookCodesController.php
> +class CodebookCodesController extends Controller
Usually, I use class names to describe only the entities involved in the process. Narrowing the class name to `CodebookCodesImportController` might imply that it only handles importing, which isn’t the case, and it opens future functions on those entities.

I'll make sure this is clear in the backend docs.

2024-05-30 11:57 UTC, alessandrobelli commented on web/composer.json
> +        "ext-simplexml": "*"
I will check if ext-simplexml is necessary in composer.json, or if I can set a version number, because [it's a PHP extension](https://www.php.net/manual/en/book.simplexml.php)

2024-06-04 17:41 UTC, jankapunkt approved these changes

2024-06-04 17:41 UTC, jankapunkt commented
@alessandrobelli you can merge from my end. However the mention with the composer dependency is your call as I am not the php/laravel pro :-D

2024-06-13 14:25 UTC, hohse approved these changes
I could not find anything wrong.

2024-06-13 14:48 UTC, merged